node_frequency: 10 #Hz
topics:
  publishers:
    # Linear velocity inner-loops
    surge: "/myellow0/ref/surge"
    sway: "/myellow0/ref/sway"
    heave: "/myellow0/ref/heave"

    # Angular speed references
    yaw_rate: "/myellow0/ref/yaw_rate"

    # Orientation references
    yaw: "/myellow0/ref/yaw"

    # Depth references
    depth: "/myellow0/ref/depth"

  subscribers:
    state: "/myellow0/nav/filter/state"