# Farol Full Path Message

# Header Information
Header header
# Reference point
geometry_msgs/Point RefPoint
# Type of path
int8[] type
# Initial Point
geometry_msgs/Point[] StartPoint
# Center Point
geometry_msgs/Point[] CenterPoint
# End Point
geometry_msgs/Point[] EndPoint
# Direction of the path
int8[] adirection
# Desired velocity
float32 velocity
# Gamma start
float32[] Gamma_s
# Gamma end
float32[] Gamma_e
