site_name: Nav Tools

nav:
  - Reference: "README.md"
  - Nodes:
    - auvstate2mstate: "auvstate2mstate.md"
    - gnss2utm: "gnss2utm.md"
    - gnss2utmoutlier: "gnss2utmoutlier.md"
    - usblfix2pos: "usblfix2pos.md"