auv_sim:

  # General simulation environment constants
  fluid_density: 1.025 # (kg/l)

  # Vehicle dynamic parameters
  vehicle:
    mass: 10.5 # (kg)
    zg: 0.0 # center of gravity in body axis (m)
    vehicle_density: 1.0 # TO DEFINE LATER
    inertia_tensor: [1000.0, 1000.0, 4.14]  # diagonal (3x3) moment of inertia matrix (kg/m2)
    linear_damping_tensor: [-0.1213, -1.1732, -1.1130, -0.5, -0.5, -0.5] # diagonal (6x6) matrix with linear damping
    quadratic_damping_tensor: [-23.9, -46.27, -50.278,  -1.0, -1.0, -1.0] # diagonal (6x6) matrix with quadratic damping
    added_mass_tensor: [27.08, 25.952, 29.9081, 1.0, 1.0, 1.0] # diagonal (6x6) matrix with added mass terms

    actuators:
      # For each thruster [Fx, Fy, Fz, lx, ly, lz] where F = forces and l = moments arms
      # and each line of the matrix represents a thruster
      allocation_matrix: [0.707, -0.707,  0.0,  0.1355,     0.1, 0.0725,     # Thruster 1
                        0.707,  0.707,  0.0,  0.1355,    -0.1, 0.0725,     # Thruster 2
                       -0.707, -0.707,  0.0, -0.1475,     0.1, 0.0725,     # Thruster 3
                       -0.707,  0.707,  0.0, -0.1475,    -0.1, 0.0725,     # Thruster 4
                        0.000,  0.000, -1.0,  0.1200,    0.22,  0.005,     # Thruster 5
                        0.000,  0.000, -1.0,  0.1200,   -0.22,  0.005,     # Thruster 6
                        0.000,  0.000, -1.0, -0.1200,    0.22,  0.005,     # Thruster 7
                        0.000,  0.000, -1.0, -0.1200,   -0.22,  0.005]     # Thruster 8

      # Thrusters parameter
      lump_param_positive: [0.00000177778, 0.0, 0.0]  # (a*|x|^{2} + b*|x| + c)
      lump_param_negative: [-0.00000177778, 0.0, 0.0] # (a*|x|^{2} + b*|x| + c)

      max_input: 100 # Maximum normalized input value
      min_input: 8.6 # Minimum normalized input value (for values < |min_input|) the motors "won't" spin <-> dead-zone

      # A gain used to scale the applied normalized input thrust (in this case used to convert from % to RPM)
      # This gain is mainly used to convert between scales
      gain: 45

      # Model of each thruster is the same as for a regular DC motor (pole+delay)
      pole: 7.2115
      delay: 0.345 # s

  # Oceans currents as a gaussian process
  current:
    mean: [0.0, 0.0, 0.0]
    sigma: [0.0, 0.0, 0.0]
    minimum: [0.0, 0.0, 0.0]
    maximum: [0.0, 0.0, 0.0]


world_frame: "world"
base_link: "base_link"

sensors:
    originLat: 38.765852
    originLon: -9.09281873
    water_column: 100
    sensors:
        - type     : "GNSS"
          frame_id : "gnss"
          frequency: 10.0
          count    : 0        # After n measumerements sensor is discarded
          noise    : 0.00
          variance : 0.03
          debug    : true     # Full gps even when diving
        - type     : "DVL_BT"
          frame_id : "dvl_bt"
          frequency: 5.0
          noise    : 0.10
          variance : 0.05
          altitude : 30.0
          debug    : true     # works regardless of depth
          count    : 0
        - type     : "DVL_WT"
          frame_id : "dvl_wt"
          frequency: 5.0
          noise    : 0.01
          variance : 0.0
          altitude : 110.0
          count    : 0        # After n measumerements sensor is discarded
        - type     : "AHRS"
          frame_id : "ahrs"
          frequency: 5.0
          noise    : [0.051, 0.017]
          variance : 0.001
        - type     : "DEPTH"
          frame_id : "depth"
          frequency: 5.0
          noise    : 0.01
          variance : 0.005
          count    : 0        # After n measumerements sensor is discarded
        - type     : "ALTIMETER"
          frame_id : "altimeter"
          frequency: 5.0
          noise    : 0.1
          variance : 0.01
          count    : 0
        - type     : "MODEL"
          frequency: 10.0
