site_name: Farol ROS messages

nav:
  - Messages List: "index-msg.md"
  - CpfFeedback: "CpfFeedback.md"
  - CPFGamma: "CPFGamma.md"
  - Currents: "Currents.md"
  - Formation: "Formation.md"
  - mPFollowingDebug: "mPFollowingDebug.md"
  - mPidDebug: "mPFollowingDebug.md"
  - mState: "mState.md"
  - Multisection: "MultiSection.md"
  - MultiTrackingsection: "MultiTrackingSection.md"
  - mUSBLFix: "mUSBLFix.md"
  - ProcessState: "ProcessState.md"
  - Section: "Section.md"
  - TrackingSection: "TrackingSection.md"
