site_name: Farol ROS messages

nav:
  - Reference: "README.md"
  - Messages List:
    - CpfFeedback: "CpfFeedback.md"
    - CPFGamma: "CPFGamma.md"
    - Currents: "Currents.md"
    - Formation: "Formation.md"
    - mPFollowingDebug: "mPFollowingDebug.md"
    - mPidDebug: "mPidDebug.md"
    - mState: "mState.md"
    - Multisection: "MultiSection.md"
    - MultiTrackingsection: "MultiTrackingSection.md"
    - mUSBLFix: "mUSBLFix.md"
    - ProcessState: "ProcessState.md"
    - Section: "Section.md"
    - TrackingSection: "TrackingSection.md"
