modem/modem_config:
    tcp_config/ip: 10.42.10.4
    local_address: 3 
    hasAHRS: false
    initializer: "{'@ZA': '1', '@ZX': '1'}"

pinger:
    tslack: 1.0
    modem_name: "10.42.10.0"
    modems_list: []
    timeout_list: []

silent:
    tslack: 1.0     # in seconds
    # modem_name: 10.42.10.6    ?????????
    #modems_list: ["1", "2"]
    modems_list: ["1","3"]
    slot_list: [5.0, 5.0]   # in seconds
    modem_id: 3
    anchor: 1
    tnew_start: 30      # in seconds

data_serializer:
    vehicle_id: 3

pos2sim_modem:
    ip: 10.42.10.4
    vehicle_name: "mdock0"

dmac2farol:
    # [Roll, Pitch, Yaw], in radians - these angles correspond to the 
    # rotation from Body to USBL frame (check documentation)
    installation_matrix: [0, 0, 0]
    # true   -  USBL has AHRS: inertial bearing/elevation are available in 
    #           measurement from DMAC (in simulation, this is true)
    # false  -  USBL does not have AHRS: bearing/elevation are only available
    #           in local (USBL) frame
    usbl_has_AHRS: true

