# TODO: all of this should be a in a vehicle specific docking.yaml

filter:
  node_frequency: 10
  usbl_outlier_rejection: true
  dvl_outlier_rejection: true
  debug: true

  horizontal:
    initial_cov: [1,0,0,0,
                  0,1,0,0,
                  0,0,1,0,
                  0,0,0,1]
    process_noise: [0.1, 0, 0,   0,
                    0, 0.1, 0,   0,
                    0, 0, 0.01, 0,
                    0, 0, 0, 0.01]
    measurement_noise: [1, 0,
                        0, 1]
    outlier_treshold: 4.61
                        
  rotational:
    initial_cov: 0.5
    process_noise: 0.1
    measurement_noise: 0.1
    outlier_treshold: 2.71
  
  vertical:
    initial_cov: 0.2
    process_noise: 0.1
    measurement_noise: 0.01
    outlier_treshold: 2.71


controller:
  node_frequency: 10
  fully_actuated: true
  debug: true
  params: [0.7, 0.1] # ksi, omega_0
  # TODO: put here velocity

mock_usbl:
  sim_usbl: false
  outliers: false
  noise: false
