# TODO: all of this should be a in a vehicle specific docking.yaml

###############################
# DOCKING FILTER
###############################
filter:
  node_frequency: 10
  debug: true
  dock_has_ahrs: false
  dock_usbl_instalation_offset: [0,0,0] # position of the USBL in the D-frame measured from D-frame to USBL-frame
  auv_usbl_instalation_offset: [0,0,0] # position of the USBL in the B-frame measured from B-frame to USBL-frame
  initializer_size: 4
  outlier_rejection:  [0,0,0]
  use_dvl_filt_in_controller: false

  position:
    process_noise: 0.01
    measurement_noise: 0.05
    outlier_threshold: 16.0 # Choose a gate (3 DoF): 90% -> 4.61 95% -> 7.815, 99% -> 11.345
    update_delay: 2.1 #1.8  # time in seconds, before all angles are received, when the update should be done

  attitude:
    gains:
      k1: 0.6
      k2: 0.4
      kp: 0.8
      ki: 0
    outlier_threshold: 16.0
    update_delay: 1.0 #0.9     # time in seconds, before all angles are received, when the update should be done

  realistify: false
  outage_bearing_dock: 2.0944
  outage_elevation_auv: 0.12

###############################
# DOCKING OUTER LOOP STATE MACHINE
###############################
outer_loop:
  node_frequency: 10
  # initial estimate of the docking position, at least one of utm/lat_lon and one of depth/altitude must be specified
  dock_utm: [4290794, 491936]
  # dock_lat_lon: [38.765824, 9.092815]
  # dock_depth: 2.87
  # dock_altitude: 1
  # this is the orientation of dock opening, so its the direction oposite to the D frame
  dock_heading: 180
  safe_depth_approach: 0.5
  safe_altitude_approach: 2.0
  aproach_dist: 10.0

  terminal_dist: 1.0    # distance [m] to ignore filter
  terminal_thrust: 1.5    # distance [m] to ignore filter
  acomms_timeout: 2    # time [s] after which returns to "search_acomms"
  acomms_n_min_fix: 3   # idk to be fair
  acomms_search_radius: 10  # radius around the docking station to seach for acomms

  ## Trajectory parameters
  homing_dist: 3       # distance [m] along the x-axis where to place homin point
  u_terminal: 0.05      # terminal velocity
  v_max_u: 0.3  # [m/s]
  v_max_v: 0.1  # [m/s]
  a_max_t: 0.05  # [m/s²]
  w_max: 0.1    # [m/s]
  a_w_max: 0.05  # [m/s²]
  r_max: 0.1    # [rad/s]
  a_r_max: 0.05  # [rad/s²]
  jerk_ratio: 0.2 # 1/value*accl is actual jerk



###############################
# TRAJECTORY TRACKING CONTROLLER
###############################
trajectory_tracking:
  type: "se3_tracker"

  se3:
    # Gains (acceleration domain!)
    Kpp:  [0.972, 0.972, 0.972]
    Kdv:  [2.52, 2.52, 2.52]
    Kip:  [0.189, 0.189, 0.189]

    KpR:  [0.972, 0.972, 0.972]
    Kdw:  [2.52, 2.52, 2.52]
    KiR:  [0.189, 0.189, 0.189]

    # Derivative filters (Hz)
    fc_v: [5.0, 5.0, 4.0]
    fc_w: [5.0, 5.0, 5.0]

    # Anti-windup (start off; turn on if you hit limits)
    kaw_v: [0.0, 0.0, 0.0]
    kaw_w: [0.0, 0.0, 0.0]

    # Model 
    # MEDUSA
    # M_diag: [50, 60.0, 100] 
    # Jdiag: [1.0, 1.0, 4.64]
    #BLUEROV
    M_diag: [17.0, 24.0, 26.0] 
    Jdiag: [0.33, 0.33, 0.33]


    # Dlin:  [0.2, 55.1, 6.4369]  
    # Dang:  [0.0, 0.0, 4.14]

    # Wrench limits (pre-allocator)
    Fmin: [-20, -20, -20]
    Fmax: [ 20,  20,  20]
    Mmin: [-2,  -2,  -2]
    Mmax: [ 2,   2,   2]



###############################
# DOCKING HELPER NODE
###############################
docking_helper:
  sim_usbl: false
  outliers: false
  noise: false

