site_name: Path Following

nav:
  - Reference: "README.md"
  - Nodes:
    - path_following: "path_following.md"
  - Services:
    - ResetVT: "ResetVT.md"
    - SetPF: "SetPF.md"
    - StartPF: "StartPF.md"
    - StopPF: "StopPF.md"
    - UpdateGainsPF: "UpdateGainsPF.md"
  